In [1]:
import numpy as np


In [4]:
X_train = np.array([[2104,5,1,45],
                   [1416,3,2,40],
                   [852,2,1,35]])
y_train = np.array([460,232,178])
print(X_train)
print(y_train)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
[460 232 178]


In [5]:
#initializing the weights and bias(i don;t know how the values were chosen)
b_init  =785.1811367994083
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])


In [ ]:
# predicting values traditionally with the for loop
def predict_one_loop(x,w,b):
    n = x.shape[0]
    p = 0
    for i in range(n):
        p_i = x[i] * w[i]
        p = p +p_i
    p = p +b
    return p


In [ ]:
#predicting a single value with the vector dot function
def predict(x,w,b):
    p = w.dot(x) + b
    return p

In [19]:
x_vec = X_train[0, :]
print(x_vec)

# make a prediction
fwb = predict_one_loop(x_vec,w_init,b_init)
print(fwb)

fwb2 = predict(x_vec,w_init,b_init)
print(fwb2)


[2104    5    1   45]
459.9999976194083
459.9999976194083


In [31]:
# COST FUNCTION

def cost_function(X,y,w,b):
    m = X.shape[0]
    cost = 0.0
    for i in range(m):
        fwb_i = np.dot(X[i], w) + b
        cost = cost + (fwb_i - y[i])**2
    return cost/(2 * m)
    


In [33]:
cost = cost_function(X_train,y_train,w_init,b_init)
print(cost)

1.5578904045996674e-12


In [55]:
# Compute gradient with multiple variables

def compute_gradient (X,y,w,b):
  m,n  = X.shape
  dj_dw = np.zeros(n)
  dj_db = 0
  for i in range(m):
    err =  (np.dot(X[i], w) + b) - y[i]
    for j in range(n):
      dj_dw[j] = dj_dw[j] + err * X[i][j]
    dj_db = dj_db + err
  dj_dw = dj_dw/m
  dj_db = dj_db/m  
  return dj_db, dj_dw


In [56]:
# test derivatives

tmp_dj_db, tmp_dj_dw = compute_gradient(X_train, y_train, w_init, b_init)

print(f'{tmp_dj_db}DJ_DB')
print(f'{tmp_dj_dw}DJ_DW')

-1.6739251122999121e-06DJ_DB
[-2.72623574e-03 -6.27197255e-06 -2.21745574e-06 -6.92403377e-05]DJ_DW


In [61]:
#Gradient Descend

def gradient_descend(X,y,w_in,b_in,gradient_function,alpha,num_iters):

    w = w_in
    b = b_in
    for i in range(num_iters):
        dj_db, dj_dw = gradient_function(X,y,w,b)
        w = w - alpha * dj_dw
        b = b - alpha * dj_db
    return w,b

In [62]:
alpha = 5.0e-7
num_iters = 1000
w_final, b_final = gradient_descend(X_train,y_train,w_init,b_init, compute_gradient,alpha, num_iters)

print(w_final,b_final)

[  0.39133535  18.75376741 -53.36032453 -26.42131618] 785.1811367994089
