In [28]:
import numpy as np
import time 

a  = np.arange(10000000)
a[-1]

try:
    a[asd]
    print(a[-1])
except Exception as e:
    print('NIGGER NIGGER NIGGER NIGGER🇷🇴')
    print(e)

x1 = a[:20]  # SLICING [START:STOP:STEP]

x1

NIGGER NIGGER NIGGER NIGGER🇷🇴
name 'asd' is not defined


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
def my_dot(a,b):
    x = 0
    for i in range(a.shape[0]):
       x = x + a[i] * b[i]
    return x
       

In [242]:
#np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
print(f'THIS IS A:----->{a}')
b = np.random.rand(10000000)
print(f'THIS IS B:---->{b}')
tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

THIS IS A:----->[0.44236513 0.04997798 0.77390955 ... 0.75330047 0.55914556 0.55274465]
THIS IS B:---->[0.92840616 0.47835747 0.39607298 ... 0.8173383  0.57980215 0.74800318]
np.dot(a, b) =  2500004.2171
Vectorized version duration: 3.6180 ms 
my_dot(a, b) =  2500004.2171
loop version duration: 1100.2469 ms 


In [237]:
 np.random.seed(9000)
a = np.random.rand(5)
a

array([0.29222481, 0.98730699, 0.8791066 , 0.39042672, 0.01184493])

In [ ]:
paul = np.arange(548967).reshape(9631,-1)  # -1 ia in cazul de fata valoarea 57. wildcard
print(paul)
print(paul.shape)

[[     0      1      2 ...     54     55     56]
 [    57     58     59 ...    111    112    113]
 [   114    115    116 ...    168    169    170]
 ...
 [548796 548797 548798 ... 548850 548851 548852]
 [548853 548854 548855 ... 548907 548908 548909]
 [548910 548911 548912 ... 548964 548965 548966]]
(9631, 57)


In [411]:
a = np.arange(100).reshape(20,-1)
b = a[2, 0:5:1]
c = a[2:3 , 0:5:1]
d = a[3:5,0:5:1]
print(b)
print(c)
print(d)
print(b.shape)
print(c.shape)
print(d.shape)


[10 11 12 13 14]
[[10 11 12 13 14]]
[[15 16 17 18 19]
 [20 21 22 23 24]]
(5,)
(1, 5)
(2, 5)


In [439]:
big_matrix = np.arange(10000).reshape(100,-1)



slice1 = big_matrix[10:20:2,60:66:1]
print(slice1)
print(slice1.shape)
print('SLICE 1 INCOMINGGGGGGGGGGGGGGGGGGG 🫥---------------------')

[[1060 1061 1062 1063 1064 1065]
 [1260 1261 1262 1263 1264 1265]
 [1460 1461 1462 1463 1464 1465]
 [1660 1661 1662 1663 1664 1665]
 [1860 1861 1862 1863 1864 1865]]
(5, 6)
SLICE 1 INCOMINGGGGGGGGGGGGGGGGGGG 🫥---------------------
