In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import make_blobs
from lab_utils_common import dlc
from lab_utils_softmax import plt_softmax



In [2]:
def soft_max(z):
    ez = np.exp(z)
    sm = ez/np.sum(ez)
    return (sm)

In [3]:
centers = [[-5,2],[-2,-2],[1,2],[5,-2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0, random_state=30)

In [4]:
print(y_train)
print(X_train)

[2 0 0 ... 1 3 2]
[[ 1.56  0.85]
 [-5.34  1.03]
 [-4.09  0.68]
 ...
 [-0.84 -1.95]
 [ 5.04 -2.92]
 [ 0.38  1.5 ]]


In [10]:
# 1. initialing the model

model = Sequential(
    [
        Dense(25, activation='relu'),
        Dense(15, activation='relu'),
        Dense(4,  activation='softmax')
    ]
)

# 2. compiling

model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(0.001)
)

# 3. fitting the model on our training data

model.fit(
    X_train,y_train,
    epochs=10
)






Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 525us/step - loss: 1.2548 
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - loss: 0.6148
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - loss: 0.2595
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 398us/step - loss: 0.0868
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - loss: 0.0677
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 396us/step - loss: 0.0515
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step - loss: 0.0498
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - loss: 0.0432
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - loss: 0.0409
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 403us/step - loss: 0.0437


In [12]:
predicted_example_1 = model.predict(X_train)
print(predicted_example_1[:2])

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step
[[1.53e-03 3.12e-04 9.88e-01 1.04e-02]
 [9.94e-01 5.15e-03 2.73e-04 7.59e-05]]


In [17]:
#now let's do the preferred , more ACCURATE S0ftmax version


#1 initializing the architecture of the model
prefered_model = Sequential(
    [
        Dense(25, activation='relu'),
        Dense(15,activation='relu'),
        Dense(4, activation = 'linear')
    ]
)

# compiling the model

prefered_model.compile(    
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),  #<-- Note
    optimizer = tf.keras.optimizers.Adam(0.001)
)




# fitting the model


In [18]:
# 3 fitting the model

prefered_model.fit(X_train, y_train, epochs=10)

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 552us/step - loss: 1.1761 
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 465us/step - loss: 0.4479
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 401us/step - loss: 0.1866
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - loss: 0.1009
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - loss: 0.0865
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 401us/step - loss: 0.0628
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 400us/step - loss: 0.0522
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 401us/step - loss: 0.0497
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - loss: 0.0431
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 537us/step - loss: 0.0335


In [20]:
# inference
prefered_predictions = prefered_model.predict(X_train)

print(prefered_predictions [:2])

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 306us/step
[[-1.93 -2.69  2.88 -1.81]
 [ 0.33 -5.18 -7.9  -9.25]]


In [25]:
# note that this values are NOT PROBABILITIES
# if you want the output to be probabilities, there is one more step
# we need to use softmax on the output like so:

softmax_prefered = tf.nn.softmax(prefered_predictions).numpy()

print(softmax_prefered[:2])

[[7.95e-03 3.70e-03 9.79e-01 8.99e-03]
 [9.96e-01 4.05e-03 2.67e-04 6.86e-05]]
